# Generated by Django 5.2.4 on 2025-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_remove_patient_scan_patient_conclusion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='scan_image',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_part',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ref_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='scan_type',
            field=models.CharField(choices=[('Xray', 'Xray'), ('CT', 'CT'), ('MRI', 'MRI'), ('MG', 'MG')], default='Xray', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('FINAL', 'Final'), ('DRAFT', 'Draft'), ('UNREAD', 'Unread')], default='UNREAD', max_length=10),
        ),
    ]
