# Generated by Django 5.2.4 on 2025-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0005_remove_report_patient_remove_patient_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="ref_by",
            field=models.CharField(default="Doctor Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="scan_image",
            field=models.ImageField(default="default.png", upload_to="scans/"),
        ),
    ]
