# Generated by Django 5.2.4 on 2025-10-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0010_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("userid", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=256)),
                ("usertype", models.CharField(blank=True, max_length=50, null=True)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("status", models.CharField(default="ACTIVE", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
