# Generated by Django 5.2.4 on 2025-10-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0014_patient1_delete_useraccount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Patient1",
        ),
    ]
