# Generated by Django 5.2.4 on 2025-10-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0016_userprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="UserAccount",
        ),
    ]
