# Generated by Django 5.2.4 on 2025-10-16 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0017_rename_userprofile_useraccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
