# Generated by Django 5.2.4 on 2025-10-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0018_useraccount_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
