
# Generated by Django 5.2.4 on 2025-10-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0020_patient_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="med.useraccount",
            ),
        ),
    ]
