# Generated by Django 5.2.4 on 2025-10-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0024_patient_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
