# Generated by Django 5.2.4 on 2025-10-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0025_patient_assigned_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="assigned_at",
        ),
    ]
