# Generated by Django 5.2.4 on 2025-11-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0026_remove_patient_assigned_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[
                    ("RADS", "RADS"),
                    ("SUPERADMIN", "Super Admin"),
                    ("IMAGING", "IMAGING"),
                ],
                max_length=10,
            ),
        ),
    ]
