# Generated by Django 5.2.4 on 2025-11-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0028_useraccount_contact_useraccount_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="email",
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[("RADS", "RADS"), ("IMAGING", "IMAGING")], max_length=10
            ),
        ),
    ]
