# Generated by Django 5.2.4 on 2025-11-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0029_remove_useraccount_contact_remove_useraccount_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[
                    ("RADS", "RADS"),
                    ("SUPERADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("IMAGING", "IMAGING"),
                ],
                max_length=10,
            ),
        ),
    ]
