# Generated by Django 5.2.4 on 2025-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0032_alter_useraccount_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[
                    ("RADS", "RADS"),
                    ("SUPERADMIN", "SUPERADMIN"),
                    ("ADMIN", "ADMIN"),
                    ("IMAGING", "IMAGING"),
                ],
                max_length=10,
            ),
        ),
    ]
