# Generated by Django 5.2.4 on 2025-11-08 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0035_alter_useraccount_options_alter_useraccount_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraccount",
            options={},
        ),
        migrations.AlterModelManagers(
            name="useraccount",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="email",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="username",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[("RADS", "RADS"), ("IMAGING", "IMAGING")], max_length=10
            ),
        ),
    ]
