# Generated by Django 5.2.4 on 2025-11-08 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=100)),
                ("userid", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "usertype",
                    models.CharField(
                        choices=[("RADS", "RADS"), ("IMAGING", "IMAGING")],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("center", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=1)),
                ("history", models.TextField()),
                ("scan_type", models.CharField(max_length=10)),
                ("body_part", models.CharField(default="Head", max_length=100)),
                ("ref_by", models.CharField(default="Doctor Unknown", max_length=100)),
                ("scan_image", models.TextField()),
                ("entry_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="UNREAD", max_length=10)),
                ("report", models.TextField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_patients",
                        to="med.useraccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="med.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "patients",
            },
        ),
    ]
