# Generated by Django 5.2.4 on 2025-10-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('history', models.TextField()),
                ('scan_type', models.CharField(max_length=20)),
                ('body_part', models.CharField(max_length=50)),
                ('ref_by', models.CharField(max_length=100)),
                ('scan', models.TextField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=10)),
            ],
        ),
    ]
