# Generated by Django 5.2.4 on 2025-11-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[
                    ("RADS", "RADS"),
                    ("IMAGING", "IMAGING"),
                    ("SUPERADMIN", "SUPERADMIN"),
                    ("ADMIN", "ADMIN"),
                ],
                max_length=10,
            ),
        ),
    ]
