# Generated by Django 5.2.4 on 2025-11-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0003_alter_useraccount_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "SUPER ADMIN"),
                    ("ADMIN", "ADMIN"),
                    ("RADS", "RADS"),
                    ("IMAGING", "IMAGING"),
                ],
                max_length=15,
            ),
        ),
    ]
