# Generated by Django 5.2.4 on 2025-10-12 04:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_remove_patient_scan_image_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ref_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='report',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='signature',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(default='Unknown Address', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='scan_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 10, 12, 4, 34, 54, 746124, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='scan_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='Unpaid', max_length=20)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('rads_score', models.CharField(max_length=20)),
                ('conclusion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.patient')),
            ],
        ),
    ]
