# Generated by Django 5.2.4 on 2025-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0004_remove_patient_body_part_remove_patient_conclusion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="address",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="scan_date",
        ),
        migrations.AddField(
            model_name="patient",
            name="body_part",
            field=models.CharField(default="Head", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="history",
            field=models.TextField(default="No history"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="ref_by",
            field=models.CharField(default="Doctor Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="report",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="scan_image",
            field=models.TextField(default="default.png"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="scan_type",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(default="UNREAD", max_length=10),
        ),
        migrations.AlterModelTable(
            name="patient",
            table="patients",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
