# Generated by Django 5.2.4 on 2025-11-11 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0005_alter_useraccount_usertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2025, 11, 11, 12, 0)
            ),
            preserve_default=False,
        ),
    ]
