# Generated by Django 5.2.4 on 2025-11-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0006_patient_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="created_at",
        ),
    ]
