# Generated by Django 5.2.4 on 2025-10-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0006_alter_patient_ref_by_alter_patient_scan_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
