# Generated by Django 5.2.4 on 2025-10-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0007_alter_patient_patient_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="scan_image",
            field=models.TextField(),
        ),
    ]
