# Generated by Django 5.2.4 on 2025-11-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0008_admin_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
