# Generated by Django 5.2.4 on 2025-10-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0009_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
