# Generated by Django 5.2.4 on 2025-11-13 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0009_remove_user_created_by_delete_admin_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="parent_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_users",
                to="med.useraccount",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[("RADS", "RADS"), ("ADMIN", "Admin"), ("IMAGING", "IMAGING")],
                max_length=10,
            ),
        ),
    ]
