# Generated by Django 5.2.4 on 2025-11-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0010_useraccount_parent_admin_alter_useraccount_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[("RADS", "RADS"), ("IMAGING", "IMAGING")], max_length=10
            ),
        ),
    ]
