# Generated by Django 5.2.4 on 2025-10-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0011_useraccount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAccount",
        ),
    ]
