# Generated by Django 5.2.4 on 2025-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0011_alter_useraccount_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[
                    ("RADS", "RADS"),
                    ("IMAGING", "IMAGING"),
                    ("SUPERADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                ],
                max_length=10,
            ),
        ),
    ]
