# Generated by Django 5.2.4 on 2025-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0012_alter_useraccount_usertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperAdminCreatedUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("userid", models.CharField(max_length=200)),
                ("usertype", models.CharField(max_length=50)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
