# Generated by Django 5.2.4 on 2025-10-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0013_useraccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UserAccount",
        ),
    ]
