# Generated by Django 5.2.4 on 2025-11-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0013_superadmincreatedusers"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="default.png",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
    ]
