# Generated by Django 5.2.4 on 2025-11-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0014_useraccount_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="profile_photo",
        ),
    ]
