# Generated by Django 5.2.4 on 2025-11-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0015_remove_useraccount_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
