# Generated by Django 5.2.4 on 2025-10-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0015_delete_patient1"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("userid", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "usertype",
                    models.CharField(
                        choices=[("RADS", "RADS"), ("IMAGING", "IMAGING")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
