# Generated by Django 5.2.4 on 2025-11-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0016_useraccount_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="profile_image",
        ),
    ]
