# Generated by Django 5.2.4 on 2025-12-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0017_remove_useraccount_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="assigned_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
