# Generated by Django 5.2.4 on 2025-12-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0018_patient_assigned_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="final_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
