# Generated by Django 5.2.4 on 2025-12-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0019_patient_final_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="tat",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
