# Generated by Django 5.2.4 on 2025-10-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0019_useraccount_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="center",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
