# Generated by Django 5.2.4 on 2025-10-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0022_patient_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="assigned_to",
        ),
    ]
