# Generated by Django 5.2.4 on 2025-10-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0023_remove_patient_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_patients",
                to="med.useraccount",
            ),
        ),
    ]
